"""Build the review-only revision 71 patch from the exact revision 70 Git object."""
import copy, difflib, hashlib, json, pathlib, subprocess
BASE = '56f185e07dfafe5533df617ec1dad473ecb63f68'
OUT = pathlib.Path(__file__).resolve().parent
raw = subprocess.check_output(['git', 'show', BASE + ':specs/requirements.json']).decode()
before = json.loads(raw)
assert before['revision'] == 70
after = copy.deepcopy(before)
rows = {r['id']: r for r in after['requirements']}
reasons = {}
def replace(rid, field, old, new, reason):
    assert rows[rid]['status'] == 'approved'
    assert old in rows[rid][field], (rid, field, old)
    rows[rid][field] = rows[rid][field].replace(old, new)
    reasons[rid] = reason
def setfield(rid, field, value, reason):
    assert rows[rid]['status'] == 'approved'
    rows[rid][field] = value
    reasons[rid] = reason
def native(rid):
    for field in ['statement', 'measurement']:
        if 'USDG' in rows[rid][field]:
            replace(rid, field, 'USDG', 'native ETH', 'The selected quote and settlement asset is native ETH; preserve the existing economic rule.')

native('REQ-provider-binding-1')
for rid in ['REQ-canonical-market-1','REQ-canonical-market-4','REQ-canonical-market-5','REQ-fee-accounting-1','REQ-fee-accounting-4','REQ-fee-accounting-6','REQ-fee-accounting-7','REQ-canonical-market-7']:
    native(rid)
setfield('REQ-canonical-market-3','statement','The canonical native ETH/HKMN PoolKey uses Currency.wrap(address(0)) as currency0 and the nonzero final HKMN address as currency1. Internal native asset identity is {chainId: "4663", assetId: "native", decimals: 18}; zero-address encoding is confined to protocol boundaries. Display notation never determines ordering.','Native currency has one valid order, not two token-address permutations.')
setfield('REQ-canonical-market-3','measurement','The four buy/sell and exact-input/exact-output combinations pass with native currency0; swapped order, nonzero quote currency, wrong HKMN, and foreign PoolKey fields refuse without liability mutation.','Native currency has one valid order, not two token-address permutations.')
replace('REQ-canonical-market-4','measurement','in both address orderings','with native currency0 and with the reversed order rejected','Only native currency0 is canonical.')
replace('REQ-fee-accounting-1','measurement','all eight buy or sell by exact-input or exact-output by token-order combinations','all four buy or sell by exact-input or exact-output combinations with native currency0 and rejection of reversed currency order','Only native currency0 is canonical; existing cumulative remainder rules remain controlling.')
replace('REQ-canonical-market-7','statement','in either currency order, direction, and exactness form','with native currency0 in either direction and exactness form','Only native currency0 is canonical.')
replace('REQ-canonical-market-7','measurement','all eight ordering, direction, and exactness combinations','all four direction and exactness combinations plus rejection of reversed currency order','Only native currency0 is canonical.')
setfield('REQ-fee-accounting-3','statement','Given a beneficiary with earned liability, when that beneficiary claims to a valid caller-selected destination, then only that beneficiary liability decreases and the hook makes one successful native ETH value call for exactly the claimed wei under the existing money-path guard. The destination may spend or forward ETH during execution; a final destination balance increase is not required as payment proof. A rejected value call or failed post-call solvency check reverts the liability debit and complete claim atomically. Zero and hook-self destinations remain invalid. Beneficiary-authorized destination overloads remain available. Overclaim, wrong caller, or reentrancy leaves every liability unchanged.','ERC20 balance-delta proof is invalid for a native recipient that forwards funds; successful guarded value transfer is the correct claim effect.')
setfield('REQ-fee-accounting-3','measurement','Claim tests cover equality and plus-one boundaries, historical beneficiaries, wrong callers, beneficiary-self and third-party destinations, contract recipients that retain or forward ETH, rejecting recipients, reentrancy, forced ETH, atomic rollback, and post-call solvency; process liability remains unavailable through beneficiary claims.','Keep claim authorization and rollback while changing only the native transfer proof.')
setfield('REQ-fee-accounting-5','statement','No external interaction on the active native ETH money path can reenter a money-moving path, retain a liability debit after a rejected value call, redirect another liability, or create funded liability from an unrelated or forced ETH balance. Native collection authenticates the exact PoolManager fee take; native payout executes the exact value under the existing guard and checks solvency after the call. The 10/40/250 basis-point cumulative accounting is unchanged.','Native calls replace ERC20 return-value and token-delta failure modes on the active release only.')
setfield('REQ-fee-accounting-5','measurement','Adversarial native recipients, forced-funding harnesses, guarded claim tests and pinned static analysis report zero reentrant payment, surviving failed-call debit, unfunded accrual, post-call insolvency, or cross-liability mutation. Historical ERC20 harnesses for excluded contracts retain their semantics.','Preserve excluded legacy contracts while testing native adversaries.')
replace('REQ-operations-wallet-1','statement','amountAtomicUsdg','amountWei','The unchanged uint256 claim ABI now carries wei.')
replace('REQ-operations-wallet-1','statement','It debits and transfers atomically,','It debits and makes an exact native value call atomically,','The unchanged claim ABI now pays native ETH.')
replace('REQ-operations-wallet-1','statement','emits cycleId, amount, destination, timestamp, cap, and used-after','emits cycleId, amountWei, destination, timestamp, capWei, and usedAfterWei only after payment succeeds','A trusted post-payment event is the native internal-claim proof.')
replace('REQ-operations-wallet-2','statement','immutable Xmax of 500000 USDG expressed as {chainId: 4663, assetId: USDG, decimals: 6, amountAtomic: 500000000000}','the explicit immutable constructor-configured processClaimLimitMaxWei, whose proposed value is derived conservatively from the existing 500000 USD economic ceiling and an owner-approved launch valuation','A dollar-valued ceiling cannot be copied as an ETH atomic integer.')
replace('REQ-operations-wallet-2','statement','No limit change resets history or usage.','The initial processClaimLimit6hWei and processClaimLimitMaxWei are positive explicit wei values in the approved launch configuration; no USDG atomic integer or guessed ETH default is reused. The contract enforces these ETH ceilings without an onchain oracle; live USD spending controls remain the bot policy engine responsibility. No limit change resets history or usage.','Separate immutable ETH enforcement from live USD policy.')
replace('REQ-operations-wallet-2','measurement','immutable 500000 USDG Xmax','explicit launch-valuation-bound immutable wei maximum and rejection of missing, inconsistent, or reused USDG-unit configuration','Preserve time/count/rotation rules while changing cap units.')
setfield('REQ-launch-orchestration-2','statement','Given a completed provider graph launch, when the separate owner-signed seedCanonicalLiquidity transaction executes, then the payable call binds msg.value exactly to amount0Max in wei, native ETH is currency0, and Permit2 is used only for HKMN currency1. The existing launchAuthority caller and explicit payer refund destination are retained and need not be equal. After required HKMN approvals, read current slot0 immediately before mint and calculate exact native and HKMN debts using the pinned core TickMath and SqrtPriceMath rounding rules. Both debts must fit their maxima. PositionManager MINT_POSITION and SETTLE_PAIR receive only the exact native debt and mint the complete HKMN allocation into permanent custody. Refund exactly msg.value minus nativeDebt to payer; do not use PositionManager SWEEP, total hook balance, or a zero PositionManager balance assumption. Clear HKMN allowances atomically and refuse residual HKMN. Custody binds the minted token id only after owner, PoolKey, full range and liquidity verification. Existing or forced ETH cannot alter refund or liabilities. Before seed, HKMN remains restricted to the canonical market and the initialized empty pool cannot swap. A mint, settlement, refund or custody failure rolls back every seed-local effect while preserving the completed provider graph for an authorized retry.','Native seed needs exact value/debt/refund flow, not USDG Permit2 or balance-derived refund.')
setfield('REQ-launch-orchestration-2','measurement','Pinned real PoolManager/PositionManager tests compare exact debt rounding at boundaries and in-range prices; exercise insufficient/excess msg.value, native and HKMN maxima, existing/forced ETH in both contracts, distinct launch caller and refund payer, refund rejection, HKMN-only Permit2 cleanup, full allocation, exact range -887220 to 887220 at tick spacing 60, permanent custody, pre-seed swap refusal and graph persistence after failed seed substeps.','Exact native debt must be checked against real pinned manager behavior.')
replace('REQ-cycle-repository-1','statement','costMicroUsdg','costMicroUsd','Held cost remains a USD cost basis, not wei.')
replace('REQ-cycle-repository-1','statement','A position stores its configured USDG control value as a verified insured amount only when that amount is already the configured USDG asset; otherwise it stores the attributed purchase cost. It never converts a Solana stablecoin insured value without a frozen quote binding.','A position stores its attributed purchase cost in USD micro-units. A typed insured amount can replace that control value only with a valid exact-amount quote-derived USD valuation bound to its asset, request, digest and validity window; a Solana stablecoin amount is never assumed equal to USD. Historical committed purchase costs are not revalued when ETH moves.','Keep held cost attribution and exclude unverified USD/USDC parity.')
for field in ['statement','measurement']:
    replace('REQ-cycle-runner-3',field,'EVM USDG','EVM native ETH','Authorize the new native custody observation without migrating historical token journals.')
replace('REQ-cycle-runner-3','statement','hookemon.custody-ledger.v2 per ADR-0026','hookemon.custody-ledger.v3 with an independently finalized native balance observation','Native custody requires a new durable identity/version; old token evidence cannot prove it.')
replace('REQ-cycle-runner-3','statement','Only finalized, cycle-attributed return deltas may become an Operations USDG credit or payout basis.','Native principal and gas share the ETH asset identity but occupy separate reservation and cost buckets; spendable principal excludes the gas reserve and unpaid obligations. Only finalized cycle-attributed native payment proofs may become an Operations ETH credit or payout basis. A direct native payment is proved from the persisted signed transaction identity, exact sender, recipient, value and calldata, successful receipt and canonical finalized block; a trusted hook post-payment event proves a claim. Internal Relay return or refund proof additionally authenticates emitter runtime, request linkage, decoded recipient/value and failure propagation. Missing proof leaves proceeds unavailable. No wallet-wide delta or fabricated ERC20 Transfer event proves a native credit. Historical USDG journals remain readable but cannot resume through the native runtime or be rescaled; native cycles use fresh identities.','Native internal payment proof, separate gas/principal and historical-state refusal are required.')
replace('REQ-cycle-runner-3','statement','non-EVM-USDG','non-native-EVM','Preserve the fail-closed rule for unapproved non-native observation producers.')
replace('REQ-cycle-runner-3','measurement','non-EVM-USDG','non-native-EVM','Preserve the fail-closed rule for unapproved non-native observation producers.')
replace('REQ-cycle-runner-3','statement','Any non-native-EVM row stays on hookemon.custody-ledger.v1, or, if migrated to v2, stays permanently unvalued','Any non-native-EVM row stays on hookemon.custody-ledger.v1, or, if migrated to v2, stays permanently unvalued','Do not create a new Solana evidence producer through the ETH migration.')
replace('REQ-cycle-runner-3','measurement','a non-native-EVM row constructed as v2 remains permanently unvalued absent an approved producer.','a non-native-EVM row constructed as v2 remains permanently unvalued absent an approved producer. Native tests reject wrong request/emitter/runtime/value, failed internal calls, unrelated deposits, stale or reorged receipts, duplicate proofs, old USDG resume and any principal spending that consumes the gas reserve.','Add exact native proof negative cases.')
replace('REQ-eligibility-snapshot-1','statement','receive USDG at their own addresses','receive native ETH at their own addresses, with bounded native payout simulation before claim','Contract recipients remain eligible; native feasibility replaces token freeze checks.')
replace('REQ-direct-payout-1','statement','Operations USDG credit','Operations native ETH credit','Payout principal is native ETH.')
replace('REQ-direct-payout-1','statement','direct USDG transfers','direct native ETH value payments','Payout principal is native ETH.')
replace('REQ-direct-payout-1','statement','It marks paid only after an exact finalized delta. Frozen recipients become quarantine liabilities','It marks paid only after proof of the exact successful finalized transaction matched to persisted signed bytes/hash, source, recipient, value and calldata; a recipient may forward ETH and its ending balance is not payment proof. Rejected recipient calls become quarantine liabilities','Native transaction proof replaces token balance deltas and preserves unpaid entitlements.')
replace('REQ-direct-payout-1','statement','Frozen recipients','Rejected recipients','Native rejection replaces USDG freeze.') if 'Frozen recipients' in rows['REQ-direct-payout-1']['statement'] else None
replace('REQ-direct-payout-1','statement','frozen recipient','rejecting recipient','Preserve quarantine on native rejection.')
replace('REQ-direct-payout-1','measurement','exact recipient deltas','exact finalized native transaction identity, value and successful execution','Native payment can be forwarded by the recipient.')
replace('REQ-direct-payout-1','measurement','frozen-recipient quarantine with continuation','rejecting-recipient quarantine with continuation, failed gas counted as cost rather than principal, and no automatic retry, redirect or WETH fallback for terminal REFUSED recipients','Preserve terminal quarantine and unpaid rights without inventing a retry feature.')
replace('REQ-policy-engine-1','statement','micro-USDG','micro-USD','Policy currency is USD valuation, not transferred ETH.')
replace('REQ-policy-engine-1','statement','MicroUsdg','MicroUsd','Policy currency is USD valuation, not transferred ETH.')
replace('REQ-policy-engine-1','statement','Held value is the verified insured amount only when it is already typed as the configured USDG asset; otherwise it is the attributed purchase cost. A Collector Solana stablecoin insured amount has no frozen USDG conversion quote binding and cannot directly drive this limit.','Held value defaults to attributed purchase cost in USD micro-units. An insured value can drive the control only with an exact bound quote-derived USD valuation; neither a Solana stablecoin amount nor ETH wei is assumed to be USD.','Retain held cost basis without stablecoin parity assumption.')
replace('REQ-policy-engine-1','statement','{chainId: 4663, assetId: USDG, decimals: 6, amountAtomic: 0}','{chainId: "4663", assetId: "native", decimals: 18, amountAtomic: "0"}','The explicit zero minimum remains zero in native ETH units.')
replace('REQ-policy-engine-1','statement','It evaluates finalized observed balances and obligations separately, with unresolved principal counted once.','It evaluates finalized observed balances and obligations separately, with unresolved principal counted once. The existing USD outer rails remain 55 per unit, 165 per cycle and 495 per rolling day, with tighter owner limits preserved. Existing unit and aggregate Relay quote admission binds each USD valuation to the exact fetched request, quote digest, chain, asset, atomic amount and validity window, using integer decimal arithmetic with costs/exposure rounded up and proceeds rounded down. Committed spend remains at validated USD cost basis; unresolved liquid ETH or USDC exposure requires fresh bound valuation before additional risk and cannot double-count existing reservations. The policy separately checks exact ETH transaction maxima and the gas reserve. Missing valuation refuses new risk but not reconciliation or separately authorized recovery. The 250 USD test envelope limits external owner capital counted once, not recycled turnover or every production cycle. No second budget helper or onchain oracle is introduced.','Preserve economic caps and extend the existing engine with exact quote-based USD accounting.')
replace('REQ-policy-engine-2','statement','USDG decimals and pause or freeze state for Operations and destinations','native ETH identity and 18-decimal unit binding, funded native principal and distinct gas reserve, and bounded recipient-call feasibility','Native assets have no ERC20 decimals/pause/freeze calls.')
replace('REQ-provider-binding-4','statement','FEE-01 records the accepted 10 basis-point share to the pinned Programmable recipient on 2026-09-04.','FEE-01 retains the historical 10 basis-point decision to the pinned Programmable recipient on 2026-09-04. Current native launch admission separately proves the exact seeded full-range native ETH/HKMN model and inclusive 300 basis-point split of 250 process, 40 treasury and 10 Programmable, with no additional trading surcharge. The observed provider profile version 4.1.0 requires a separate 20 basis-point gross-native kernel with ceil-per-trade rounding and an atomic initial buy of at least 1 USD; those requirements differ from this selected model and remain open compatibility facts until exact-model admission is evidenced.','Historical fee evidence cannot establish current native custom-model admission.')

for rid in ['REQ-fee-accounting-6', 'REQ-fee-accounting-7', 'REQ-canonical-market-7']:
    for field in ['statement', 'measurement']:
        rows[rid][field] = rows[rid][field].replace('smallest native ETH units', 'wei').replace('smallest native ETH unit', 'wei').replace('atomic native ETH', 'wei')

after['revision'] = 71
# Match the baseline serialization exactly; fail rather than creating unrelated formatting churn.
enc = next((ascii_mode for ascii_mode in [False, True] if json.dumps(before, indent=2, ensure_ascii=ascii_mode)+'\n' == raw), None)
assert enc is not None, 'baseline JSON serialization changed'
new = json.dumps(after, indent=2, ensure_ascii=enc)+'\n'
changed = [r['id'] for a,r in zip(before['requirements'],after['requirements']) if a != r]
assert set(changed) == set(reasons)
assert rows['REQ-transaction-policy-1'] == next(r for r in before['requirements'] if r['id']=='REQ-transaction-policy-1')
for rid in ['REQ-provider-binding-2','REQ-release-evidence-4','REQ-phase-boundary-1']:
    assert rows[rid] == next(r for r in before['requirements'] if r['id']==rid)
patch = ''.join(difflib.unified_diff(raw.splitlines(True),new.splitlines(True),fromfile='a/specs/requirements.json',tofile='b/specs/requirements.json'))
(OUT/'revision-71.patch').write_text(patch)
manifest = {'schema':'hookemon.native-eth-interface-proposal.v1','status':'PROPOSED_NOT_AUTHORITATIVE','baseCommit':BASE,'baseRequirementsRevision':70,'baseRequirementsSha256':hashlib.sha256(raw.encode()).hexdigest(),'proposedRequirementsRevision':71,'proposedRequirementsSha256':hashlib.sha256(new.encode()).hexdigest(),'patchSha256':hashlib.sha256(patch.encode()).hexdigest(),'changes':[{'requirementId':rid,'rationale':reasons[rid]} for rid in changed],'unchangedCollectorRequirement':'REQ-transaction-policy-1','preservedHistoricalRequirements':['REQ-provider-binding-2','REQ-release-evidence-4','REQ-phase-boundary-1']}
manifest['historicalScopeMap'] = {rid: {'classification': 'HISTORICAL_SELECTED_RELEASE_EXCLUDED', 'nativeReleaseAuthority': False, 'disposition': 'Preserved unchanged; selected Phase3 deployment excludes vault/Phase1 paths and this requirement must not be used as native release authority.'} for rid in manifest['preservedHistoricalRequirements']}
manifest['providerEvidenceCommit'] = 'acce05b40340310ef76f86ea77ae23deaf5d1369'
manifest['fundingEvidenceCommit'] = '07f32246d3acb89f7df0ad552388cdcc1d5bf383'
(OUT/'proposal.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({'changedRequirements':len(changed),'baseHash':manifest['baseRequirementsSha256'],'proposedHash':manifest['proposedRequirementsSha256']}))
