import { join } from 'node:path';
import { writeFileSync } from 'node:fs';
import { writeJson } from './util.mjs';
import { listReceipts } from './receipts.mjs';
import { isGateReceiptAuthoritative } from './gates.mjs';
export { PHASES } from './phases.mjs';
import { PHASES } from './phases.mjs';

export function projectState(root) {
  const receipts = listReceipts(root);
  const phases = PHASES.map(phase => {
    const latest = [...receipts].reverse().find(r => r.type === 'gate' && r.phase === phase);
    let result = latest ? latest.result : 'PENDING';
    if (latest && ['PASSED', 'OVERRIDDEN'].includes(result)
        && !isGateReceiptAuthoritative(root, latest)) result = 'STALE';
    return { phase, result, receipt: latest?.id ?? null };
  });
  const current = phases.find(p => p.result !== 'PASSED' && p.result !== 'OVERRIDDEN')?.phase ?? 'done';
  const receiptById = new Map(receipts.map(receipt => [receipt.id, receipt]));
  const overrides = phases
    .filter(phase => phase.result === 'OVERRIDDEN')
    .map(phase => receiptById.get(phase.receipt))
    .filter(receipt => receipt && isGateReceiptAuthoritative(root, receipt))
    .map(receipt => ({
      id: receipt.id, phase: receipt.phase, rationale: receipt.data?.rationale ?? '',
    }));
  const state = { generatedAt: receipts.at(-1)?.at ?? null, currentPhase: current, phases, overrides };
  writeJson(join(root, 'state.json'), state);
  writeFileSync(join(root, 'STATE.md'), renderStateMd(state));
  return state;
}

function renderStateMd(s) {
  const rows = s.phases.map(p => `| ${p.phase} | ${p.result} | ${p.receipt ?? ''} |`).join('\n');
  const ov = s.overrides.length
    ? s.overrides.map(o => `- ${o.id} (${o.phase}): ${o.rationale}`).join('\n')
    : '- none';
  return [
    '<!-- GENERATED by `node scripts/v4.mjs status` — do not edit. Authority: receipts/ -->',
    '', '# Project State', '',
    `Current phase: **${s.currentPhase}**`, `Generated: ${s.generatedAt}`, '',
    '| Phase | Result | Receipt |', '|---|---|---|', rows, '',
    '## Overrides', ov, '',
  ].join('\n');
}
