[profile.default]
src = "src/accounting"
test = "test/feasibility"
out = "out-funding-model"
cache_path = "cache-funding-model"
libs = ["lib"]
auto_detect_remappings = false
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
